// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChOTHvk3b-9sK6V13WQUaSrv9mhHCcqrQ',
    appId: '1:268638465842:web:fa154b6066fe46489a712b',
    messagingSenderId: '268638465842',
    projectId: 'tesvikavcisi-ef866',
    authDomain: 'tesvikavcisi-ef866.firebaseapp.com',
    storageBucket: 'tesvikavcisi-ef866.firebasestorage.app',
    measurementId: 'G-CPM8KRBD8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIRcdek09lOWBaDG6OaWET7gmMcrf2rE4',
    appId: '1:268638465842:android:a78e9a2ec196f0d29a712b',
    messagingSenderId: '268638465842',
    projectId: 'tesvikavcisi-ef866',
    storageBucket: 'tesvikavcisi-ef866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTapeSMJQ9UR75yUWIltl42KBlXkXO-Lc',
    appId: '1:268638465842:ios:71bc8f387ae69b059a712b',
    messagingSenderId: '268638465842',
    projectId: 'tesvikavcisi-ef866',
    storageBucket: 'tesvikavcisi-ef866.firebasestorage.app',
    iosBundleId: 'com.example.tesvikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTapeSMJQ9UR75yUWIltl42KBlXkXO-Lc',
    appId: '1:268638465842:ios:71bc8f387ae69b059a712b',
    messagingSenderId: '268638465842',
    projectId: 'tesvikavcisi-ef866',
    storageBucket: 'tesvikavcisi-ef866.firebasestorage.app',
    iosBundleId: 'com.example.tesvikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChOTHvk3b-9sK6V13WQUaSrv9mhHCcqrQ',
    appId: '1:268638465842:web:039eca30efe98aeb9a712b',
    messagingSenderId: '268638465842',
    projectId: 'tesvikavcisi-ef866',
    authDomain: 'tesvikavcisi-ef866.firebaseapp.com',
    storageBucket: 'tesvikavcisi-ef866.firebasestorage.app',
    measurementId: 'G-L11NVLYNTS',
  );
}
